CREATE TABLE intervencoesOperacionais (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
quilometroInicial NUMBER NOT NULL,
quilometroFinal NUMBER NOT NULL,
tipoClima VARCHAR2(100) NOT NULL,
nomeEquipe VARCHAR2(100) NOT NULL
);

CREATE TABLE equipesManutencao (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nomeEquipe VARCHAR2(100) NOT NULL,
quantidadeFuncionarios NUMBER NOT NULL,
rocadaDeAtuacao VARCHAR2(100) NOT NULL
);

CREATE TABLE trechos (
id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
nome VARCHAR2(100) NOT NULL,
quilometroInicial NUMBER NOT NULL,
quilometroFinal NUMBER NOT NULL,
nivelVegetacaoEmCm NUMBER NOT NULL,
tipoClima VARCHAR2(100) NOT NULL,
trechoComSenor NUMBER(1) NOT NULL
);
